name: Build

on:
  push:
    branches:
      - master
    paths:
      - "**"
      - "!README.md"

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_tag: ${{ steps.bump_version.outputs.new_tag }}
      new_tag_major: ${{ steps.bump_version.outputs.new_tag_major }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Bump Version
        id: bump_version
        uses: Srlion/float-version-semantic@2811c4af2d8e37a37d3b8113ca5a07b4152be2fd
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: bump-version
    strategy:
      matrix:
        os: [linux, windows]
        include:
          - os: linux
            runs_on: ubuntu-22.04
            target1: i686-unknown-linux-gnu
            target2: x86_64-unknown-linux-gnu
            extra_deps: |
              sudo apt update
              sudo apt install gcc-i686-linux-gnu
              sudo apt install gcc-multilib
            binary_prefix: "lib"
            file_ext: "so"
            suffix32: _linux.dll
            suffix64: _linux64.dll
          - os: windows
            runs_on: windows-2022
            target1: i686-pc-windows-msvc
            target2: x86_64-pc-windows-msvc
            extra_deps: ""
            binary_prefix: ""
            file_ext: "dll"
            suffix32: _win32.dll
            suffix64: _win64.dll
    runs-on: ${{ matrix.runs_on }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Set up Rust
        run: rustup toolchain install stable --profile minimal

      - name: Set up rust-cache
        uses: Swatinem/rust-cache@v2

      - name: Install build dependencies
        if: matrix.os == 'linux'
        run: ${{ matrix.extra_deps }}

      - name: Add targets
        run: rustup target add ${{ matrix.target1 }} ${{ matrix.target2 }}

      - name: Install cargo-set-version
        run: cargo install cargo-set-version

      - name: Bump Cargo version
        run: cargo set-version "${{ needs.bump-version.outputs.new_tag }}.0"

      - name: Build targets
        run: |
          cargo build --release --target ${{ matrix.target1 }}
          cargo build --release --target ${{ matrix.target2 }}

      - name: Rename binaries
        run: |
          mv target/${{ matrix.target1 }}/release/${{ matrix.binary_prefix }}gmsv_goobie_mysql.${{ matrix.file_ext }} target/${{ matrix.target1 }}/release/gmsv_goobie_mysql_${{ needs.bump-version.outputs.new_tag_major }}${{ matrix.suffix32 }}
          mv target/${{ matrix.target2 }}/release/${{ matrix.binary_prefix }}gmsv_goobie_mysql.${{ matrix.file_ext }} target/${{ matrix.target2 }}/release/gmsv_goobie_mysql_${{ needs.bump-version.outputs.new_tag_major }}${{ matrix.suffix64 }}

      - name: Release Artifacts
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ needs.bump-version.outputs.new_tag_major }}"
          artifacts: |
            target/${{ matrix.target1 }}/release/gmsv_goobie_mysql_${{ needs.bump-version.outputs.new_tag_major }}${{ matrix.suffix32 }}
            target/${{ matrix.target2 }}/release/gmsv_goobie_mysql_${{ needs.bump-version.outputs.new_tag_major }}${{ matrix.suffix64 }}
